MONGODB_ADMINUSERNAME = 'mongo_user'
MONGODB_ADMINPASSWORD = 'mongo_pw'
MONGODB_HOST = '0.0.0.0:27017'
MONGODB_DBNAME = 'test_db'
MONGODB_URI = f'mongodb://{MONGODB_ADMINUSERNAME}:{MONGODB_ADMINPASSWORD}@{MONGODB_HOST}/?authMechanism=SCRAM-SHA-1'

